name: ses
channels:
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.4=pyh9f0ad1d_0
  - ca-certificates=2020.12.5=h033912b_0
  - certifi=2020.12.5=py39h6e9494a_1
  - cycler=0.10.0=py_2
  - dill=0.3.3=pyhd8ed1ab_0
  - freetype=2.10.4=h4cff582_1
  - jpeg=9d=hbcb3906_0
  - kiwisolver=1.3.1=py39hedf5dff_1
  - lcms2=2.12=h577c468_0
  - libblas=3.9.0=8_openblas
  - libcblas=3.9.0=8_openblas
  - libcxx=11.1.0=habf9029_0
  - libffi=3.3=h046ec9c_2
  - libgfortran=5.0.0=9_3_0_h6c81a4c_19
  - libgfortran5=9.3.0=h6c81a4c_19
  - liblapack=3.9.0=8_openblas
  - libopenblas=0.3.12=openmp_h54245bb_1
  - libpng=1.6.37=h7cec526_2
  - libtiff=4.2.0=h355d032_0
  - libwebp-base=1.2.0=hbcf498f_0
  - llvm-openmp=11.0.1=h7c73e74_0
  - lz4-c=1.9.3=h046ec9c_0
  - matplotlib=3.3.4=py39h6e9494a_0
  - matplotlib-base=3.3.4=py39hc986735_0
  - multiprocess=0.70.11.1=py39hcbf5805_1
  - ncurses=6.2=h2e338ed_4
  - nose=1.3.7=py_1006
  - numpy=1.20.1=py39h3c955ea_0
  - olefile=0.46=pyh9f0ad1d_1
  - openssl=1.1.1j=hbcf498f_0
  - pandas=1.2.3=py39h4d6be9b_0
  - pathos=0.2.7=pyhd3deb0d_0
  - pillow=8.1.2=py39h5fdd921_0
  - pip=21.0.1=pyhd8ed1ab_0
  - ply=3.11=py_1
  - pox=0.2.9=pyhd3deb0d_0
  - ppft=1.6.6.3=pyhd3deb0d_0
  - pyomo=5.7.3=py39h219cf5c_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - python=3.9.2=h2502468_0_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.9=1_cp39
  - pytz=2021.1=pyhd8ed1ab_0
  - pyutilib=6.0.0=pyh9f0ad1d_0
  - readline=8.0=h0678c8f_2
  - scipy=1.6.0=py39hed629a4_0
  - setuptools=49.6.0=py39h6e9494a_3
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.34.0=h17101e1_0
  - tk=8.6.10=h0419947_1
  - tornado=6.1=py39hcbf5805_1
  - tzdata=2021a=he74cb21_0
  - wheel=0.36.2=pyhd3deb0d_0
  - xz=5.2.5=haf1e3a3_1
  - zlib=1.2.11=h7795811_1010
  - zstd=1.4.9=h582d3a0_0
